CREATE TABLE Genre(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Book (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	publication_year INTEGER CHECK(
		publication_year > 0 
		AND publication_year <= EXTRACT(YEAR FROM CURRENT_DATE) + 1
	),
	isbn VARCHAR(13) UNIQUE,
	status VARCHAR NOT NULL DEFAULT 'AVAILABLE' CHECK(
		status in ('AVAILABLE', 'READ', 'IN_PROGRESS')
	)
);


CREATE TABLE Book_Genre(
	book_id INTEGER NOT NULL,
	genre_id INTEGER NOT NULL,
	PRIMARY KEY(book_id, genre_id),
	FOREIGN KEY(book_id) REFERENCES Book(id) ON DELETE CASCADE,
	FOREIGN KEY(genre_id) REFERENCES Genre(id) ON DELETE CASCADE
);

CREATE TABLE Review(
	id SERIAL PRIMARY KEY,
	content TEXT,
	rating INTEGER NOT NULL CHECK(rating >=1 AND rating <=5),
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	book_id INTEGER NOT NULL,
	FOREIGN KEY(book_id) REFERENCES Book(id) ON DELETE CASCADE
);